---
title: "Adventr"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Another Alternative

There is a package you can use to learn R called adventr. adventr is a tutorial package created in R by Andy Field to accompany his rather unusual book starring a guy named Zach and a sarcastic cat. This tutorial uses the tidyverse rather heavily and gets into statistics earlier than the swirl tutorials do. You might find that this suits you better—and then again, you might find yourself lost and frustrated by it, in which case I suggest you go back to using swirl.

Here is how to install and use adventr:

1. At the console, install the package by typing:  
      `install.packages(“devtools”) # unless you have done this`  
      `library(devtools)`  
      `install_github(“profandyfield/adventr”)`  

2. Load the library by typing:  
      `library(adventr)`

3. Run the first lesson by typing:  
      `learnr::run_tutorial("adventr_02", package = "adventr")`

No idea why it’s 02 instead of 01. But it is. Please contact me if these steps don’t work for you.	You can either read the background material about Andy Field’s book (a comic book for teaching R and statistics in R? Yes.) by following its link or read the information on the html page that opens and press continue or next topic. Along the way, you will encounter boxes where you can enter R code and see how it works. Once you get past adventr_02, the statistics begin, so you might want to stop after that. If you plan to attend the R statistics workshops and you like Any Field’s style of teaching, go on with the lessons."